from .sample_ai import SampleAi
from .random_ai import RandomAi, RandomAi2, RandomAi3
from .montecarlo_ai import Montecarlo
from .montecarlo_choose_diagonal_lines_first import MontecarloChooseDiagonalLinesFirst
from .montecarlo_choose_places_other_than_diagonal_lines_first import MontecarloChoosePlacesOtherThanGiagonalLinesFirst
from .montecarlo_ai_PrioritizedDraw import MontecarloPrioritizedDraw
from .montecarlo_ai_PrioritizedDrawC1 import MontecarloPrioritizedDrawC1
from .montecarlo_ai_PrioritizedDrawC3 import MontecarloPrioritizedDrawC3
from .montecarlo_ai_UnifiedUcbCalc import MontecarloUnifiedUcbCalc
from .montecarlo_ai_UnifiedUcbCalcC1 import MontecarloUnifiedUcbCalcC1
from .montecarlo_ai_UnifiedUcbCalcC3 import MontecarloUnifiedUcbCalcC3