from .sample_ai import SampleAi
from .random_ai import RandomAi, RandomAi2, RandomAi3
from .montecarlo_ai import Montecarlo
from .montecarlo_choose_diagonal_lines_first import MontecarloChooseDiagonalLinesFirst
from .montecarlo_choose_places_other_than_diagonal_lines_first import MontecarloChoosePlacesOtherThanGiagonalLinesFirst
from .i_love_strong_computer import ILoveStrongComputer
